/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SeamlessGitBackupPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// gitHandler.ts
var import_child_process = require("child_process");
var import_util = require("util");
var execFileAsync = (0, import_util.promisify)(import_child_process.execFile);
var GIT_TIMEOUT_MS = 6e4;
var GitError = class _GitError extends Error {
  constructor(code, message) {
    super(message);
    this.code = code;
    this.name = "GitError";
    Object.setPrototypeOf(this, _GitError.prototype);
  }
};
var GitHandler = class {
  constructor(vaultPath) {
    this.vaultPath = vaultPath;
  }
  // ── Private: safe subprocess runner ────────────────────────────────────────
  /**
   * Runs `git <args>` in the vault directory without involving a shell.
   *
   * Passing `args` as an array to `execFile` means the OS calls git directly
   * with those arguments — no shell expansion, no quoting, no injection risk.
   *
   * A race between `execFileAsync` and a manual timeout promise ensures the
   * subprocess is always killed if it hangs, even on platforms where
   * `execFile`'s own `timeout` option has inconsistent behaviour.
   *
   * @param args   - Git subcommand and flags (e.g. ["status", "--porcelain"]).
   * @param stepCode - The GitErrorCode to use if this step fails, enabling
   *                   precise per-step error attribution.
   * @returns stdout of the git invocation (trimmed).
   * @throws GitError
   */
  async git(args, stepCode) {
    let timeoutHandle;
    const timeoutPromise = new Promise((_resolve, reject) => {
      timeoutHandle = setTimeout(() => {
        reject(
          new GitError(
            "TIMEOUT",
            `Git command timed out after ${GIT_TIMEOUT_MS / 1e3}s: git ${args.join(" ")}`
          )
        );
      }, GIT_TIMEOUT_MS);
    });
    try {
      const result = await Promise.race([
        execFileAsync("git", args, {
          cwd: this.vaultPath,
          maxBuffer: 10 * 1024 * 1024
          // 10 MB — safe for large vaults
        }),
        timeoutPromise
      ]);
      return result.stdout.trim();
    } catch (error) {
      if (error instanceof GitError) throw error;
      throw this.parseExecError(error, stepCode);
    } finally {
      if (timeoutHandle !== void 0) clearTimeout(timeoutHandle);
    }
  }
  /**
   * Converts a raw `execFile` rejection into a typed `GitError`.
   *
   * We prefer inspecting `stderr` over exit codes because Git's stderr
   * strings are stable across versions; exit codes vary by platform/build.
   *
   * The optional `stepCode` parameter lets the caller pin failures from
   * specific steps (add/commit/push) to their own error code rather than
   * relying solely on stderr pattern matching, which improves precision when
   * the same stderr pattern could appear in multiple steps.
   */
  parseExecError(error, stepCode) {
    const stderr = error instanceof Error && "stderr" in error ? String(error.stderr) : "";
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes("ENOENT") || message.includes("command not found") || message.includes("not recognized")) {
      return new GitError(
        "GIT_NOT_INSTALLED",
        "Git binary not found. Install Git and ensure it is on your PATH."
      );
    }
    if (stderr.includes("not a git repository") || stderr.includes("fatal: not a git repo")) {
      return new GitError(
        "NOT_A_REPO",
        "This vault is not a Git repository. Run `git init` inside your vault folder."
      );
    }
    if (stderr.includes("No configured push destination") || stderr.includes("no upstream") || stderr.includes("does not have an upstream branch") || stderr.includes("no remote")) {
      return new GitError(
        "NO_REMOTE",
        "No Git remote configured. Add one with `git remote add origin <url>`."
      );
    }
    if (stderr.includes("Authentication failed") || stderr.includes("Permission denied (publickey)") || stderr.includes("Invalid username or password") || stderr.includes("could not read Username") || stderr.includes("Host key verification failed")) {
      return new GitError(
        "AUTH_FAILED",
        "Git authentication failed. Check your SSH key or HTTPS credentials."
      );
    }
    if (stderr.includes("Could not resolve host") || stderr.includes("Connection refused") || stderr.includes("Network is unreachable") || stderr.includes("Failed to connect") || stderr.includes("unable to access")) {
      return new GitError(
        "NETWORK_ERROR",
        "Network error. Check your internet connection and try again."
      );
    }
    if (stderr.includes("nothing to commit") || stderr.includes("nothing added to commit")) {
      return new GitError(
        "NOTHING_TO_COMMIT",
        "Nothing to commit \u2014 the working tree is clean."
      );
    }
    if (stderr.includes("rejected") || stderr.includes("non-fast-forward") || stderr.includes("Updates were rejected")) {
      return new GitError(
        "PUSH_REJECTED",
        "Push was rejected by the remote. You may need to pull first."
      );
    }
    if (stepCode) {
      return new GitError(
        stepCode,
        `Git ${args_label(stepCode)} failed: ${stderr || message}`
      );
    }
    return new GitError(
      "UNKNOWN_GIT_ERROR",
      `Unexpected Git error: ${stderr || message}`
    );
  }
  // ── Public API ───────────────────────────────────────────────────────────
  /**
   * Confirms that `git` is available on the system PATH.
   * Runs `git --version` (no side-effects) as the probe.
   *
   * @throws GitError("GIT_NOT_INSTALLED")
   */
  async checkGitInstallation() {
    return this.git(["--version"]);
  }
  /**
   * Confirms the vault root is inside a Git work tree.
   * Uses `git rev-parse --is-inside-work-tree` — the canonical check.
   *
   * @throws GitError("NOT_A_REPO")
   */
  async checkIfRepo() {
    const result = await this.git(["rev-parse", "--is-inside-work-tree"]);
    return result === "true";
  }
  /**
   * Returns the current working-tree status.
   * `--porcelain` output is machine-stable across Git versions.
   * Empty output → clean tree (no changes to back up).
   */
  async getGitStatus() {
    const rawStatus = await this.git(["status", "--porcelain"]);
    return {
      hasChanges: rawStatus.length > 0,
      rawStatus
    };
  }
  /**
   * Performs the full backup: add → (verify staged) → commit → push.
   *
   * Safety guarantees:
   *  - The commit message is passed as a discrete argv element — never
   *    interpolated into a shell string — so no sanitisation is needed and
   *    shell injection is structurally impossible.
   *  - After `git add -A` we re-query `git diff --cached --quiet` to confirm
   *    something is actually staged. If not (e.g. every changed file is in
   *    .gitignore), we throw NOTHING_TO_COMMIT rather than creating an empty
   *    commit.
   *  - Each step uses a distinct `stepCode` so error messages name the exact
   *    failing operation (staging failed / commit failed / push failed).
   *
   * @param commitMessage - The fully-resolved commit message (placeholders
   *                        already replaced). Passed verbatim to git; no
   *                        escaping required or applied.
   * @throws GitError on any step failure.
   */
  async performBackup(commitMessage) {
    await this.git(["add", "-A"], "UNKNOWN_GIT_ERROR");
    const hasStagedChanges = this.checkHasStagedChanges();
    if (!hasStagedChanges) {
      throw new GitError(
        "NOTHING_TO_COMMIT",
        "Nothing to commit \u2014 all changes are ignored or already staged."
      );
    }
    await this.git(["commit", "-m", commitMessage], "UNKNOWN_GIT_ERROR");
    await this.git(["push", "--follow-tags"], "PUSH_REJECTED");
  }
  /**
   * Returns true if the Git index contains staged changes ready to commit.
   *
   * `git diff --cached --quiet` exit code semantics:
   *   0  → index is clean (nothing staged)
   *   1  → staged changes exist          ← the EXPECTED non-zero case
   *  >1  → git itself encountered an error
   *
   * WHY spawnSync instead of promisify(execFile)?
   * promisify(execFile) rejects on ANY non-zero exit and stuffs the numeric
   * exit code into `.code` on the thrown Error — but `.code` is ALSO used by
   * Node's ErrnoException for POSIX string codes like "ENOENT". There is no
   * reliable way to distinguish "exit code 1" from "ENOENT" after the fact.
   *
   * spawnSync returns a plain result object with a `.status` field that is
   * always the raw numeric exit code (or null on signal), with no ambiguity.
   * It is synchronous, but this check is instantaneous (no I/O, pure index
   * read) so blocking the JS thread for <5 ms is acceptable.
   */
  checkHasStagedChanges() {
    var _a, _b;
    const result = (0, import_child_process.spawnSync)("git", ["diff", "--cached", "--quiet"], {
      cwd: this.vaultPath,
      // pipe stdio so the child never blocks waiting for a TTY
      stdio: "pipe",
      // 10 s hard ceiling — this command is near-instant in any healthy repo
      timeout: 1e4
    });
    if (result.error) {
      throw this.parseExecError(result.error);
    }
    const exitCode = result.status;
    if (exitCode === null) {
      throw new GitError(
        "TIMEOUT",
        "git diff --cached timed out while checking staged changes."
      );
    }
    if (exitCode === 0) {
      return false;
    }
    if (exitCode === 1) {
      return true;
    }
    const stderr = (_b = (_a = result.stderr) == null ? void 0 : _a.toString().trim()) != null ? _b : "";
    throw this.parseExecError(
      Object.assign(
        new Error(`git diff --cached --quiet exited with code ${exitCode}`),
        { stderr }
      )
    );
  }
  /** Returns the vault path this handler is bound to. */
  getVaultPath() {
    return this.vaultPath;
  }
  /**
   * Performs a `git pull` and reports whether new changes arrived.
   *
   * We parse stdout for the "Already up to date." string that Git emits when
   * there is nothing to pull. Any other non-empty stdout means new commits
   * were fetched and merged into the working tree.
   *
   * Why not `git fetch` + `git merge`?
   * `git pull` is the single command users understand and expect. For a simple
   * backup/sync workflow with no branching complexity, it is the right tool.
   *
   * @returns PullResult describing whether new changes were received.
   * @throws GitError on network failure, auth failure, merge conflict, etc.
   */
  async performPull() {
    const stdout = await this.git(["pull"], "NETWORK_ERROR");
    const alreadyUpToDate = stdout.toLowerCase().includes("already up to date");
    return {
      alreadyUpToDate,
      // Surface the raw output so callers can show it in a notice if desired.
      summary: stdout
    };
  }
};
function args_label(code) {
  var _a;
  const labels = {
    PUSH_REJECTED: "push",
    NOTHING_TO_COMMIT: "commit"
  };
  return (_a = labels[code]) != null ? _a : "operation";
}

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  commitMessageTemplate: "Vault backup: {{date}} at {{time}}",
  notifyOnNoChanges: true,
  pullOnStartup: true,
  notifyOnPull: true
};
function resolveCommitMessage(template) {
  const now = /* @__PURE__ */ new Date();
  const date = now.toISOString().split("T")[0];
  const time = now.toTimeString().split(" ")[0];
  return template.replace(/\{\{date\}\}/g, date).replace(/\{\{time\}\}/g, time);
}
var SeamlessGitBackupSettingTab = class extends import_obsidian.PluginSettingTab {
  /**
   * @param app    - The Obsidian App singleton (required by PluginSettingTab).
   * @param plugin - Our plugin instance, used to read and persist settings.
   */
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * Builds the settings UI.
   *
   * The `containerEl` property is provided by Obsidian. We clear it first
   * to avoid duplicate controls if `display()` is called multiple times.
   *
   * Each `Setting` uses method chaining to attach a name, description, and
   * interactive control. Obsidian handles the underlying DOM creation,
   * accessibility attributes, and theming automatically.
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Seamless Git Backup" });
    containerEl.createEl("p", {
      text: "Configure how your vault is committed and pushed to your Git remote.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Commit message template").setDesc(
      createFragment((frag) => {
        frag.appendText(
          "Template for the Git commit message. Supported placeholders:"
        );
        frag.createEl("br");
        frag.createEl("code", { text: "{{date}}" });
        frag.appendText(" \u2192 current date (YYYY-MM-DD),  ");
        frag.createEl("code", { text: "{{time}}" });
        frag.appendText(" \u2192 current time (HH:MM:SS)");
        frag.createEl("br");
        frag.createEl("em", {
          text: `Preview: "${resolveCommitMessage(
            this.plugin.settings.commitMessageTemplate
          )}"`,
          cls: "sgb-preview-text"
        });
      })
    ).addText(
      (text) => text.setPlaceholder("Vault backup: {{date}} at {{time}}").setValue(this.plugin.settings.commitMessageTemplate).onChange(async (value) => {
        this.plugin.settings.commitMessageTemplate = value.trim() || DEFAULT_SETTINGS.commitMessageTemplate;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Notify when vault is already up-to-date").setDesc(
      "Show a notice when you trigger a backup but there are no new changes to commit. Disable this if you find the notification distracting."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.notifyOnNoChanges).onChange(async (value) => {
        this.plugin.settings.notifyOnNoChanges = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Pull (Sync from Remote)" });
    containerEl.createEl("p", {
      text: "Pull keeps your desktop vault in sync with edits made on other devices (e.g. via the GitHub mobile app).",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Pull on startup").setDesc(
      "Automatically run `git pull` every time Obsidian opens. Ensures your vault is up-to-date before you start working."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.pullOnStartup).onChange(async (value) => {
        this.plugin.settings.pullOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show pull result notice").setDesc(
      "Show a notice after a pull completes \u2014 whether new changes arrived or the vault was already up-to-date. Disable for a fully silent startup pull."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.notifyOnPull).onChange(async (value) => {
        this.plugin.settings.notifyOnPull = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Requirements & Setup" });
    const infoList = containerEl.createEl("ul", { cls: "sgb-info-list" });
    const requirements = [
      "Git must be installed and available on your system PATH.",
      "Your vault folder must be a Git repository (run `git init` inside it).",
      "A remote must be configured (e.g. `git remote add origin <url>`).",
      "Authentication (SSH key or HTTPS token) must be pre-configured \u2014 this plugin does not handle credentials."
    ];
    for (const req of requirements) {
      infoList.createEl("li", { text: req });
    }
  }
};
function createFragment(builder) {
  const frag = document.createDocumentFragment();
  builder(frag);
  return frag;
}

// uiHandlers.ts
var import_obsidian2 = require("obsidian");
var NOTICE_DURATION_INFO = 3e3;
var NOTICE_DURATION_NORMAL = 5e3;
var NOTICE_DURATION_ERROR = 1e4;
function showBackupInProgressNotice() {
  return new import_obsidian2.Notice("\u23F3 Backup in progress\u2026", NOTICE_DURATION_INFO);
}
function showBackupSuccessNotice() {
  new import_obsidian2.Notice("\u2705 Backup complete! Changes pushed to remote.", NOTICE_DURATION_NORMAL);
}
function showNoChangesNotice() {
  new import_obsidian2.Notice("\u2139\uFE0F No changes to backup \u2014 vault is already up-to-date.", NOTICE_DURATION_NORMAL);
}
function showBackupErrorNotice(error, app) {
  const { userMessage, technicalDetail } = resolveErrorContent(error);
  const noticeText = technicalDetail ? `\u274C ${userMessage}
(Click for details)` : `\u274C ${userMessage}`;
  const notice = new import_obsidian2.Notice(noticeText, NOTICE_DURATION_ERROR);
  if (technicalDetail) {
    notice.noticeEl.addEventListener("click", () => {
      new GitErrorModal(app, userMessage, technicalDetail).open();
    });
    notice.noticeEl.addClass("sgb-notice-clickable");
  }
}
function showWarningNotice(message) {
  new import_obsidian2.Notice(`\u26A0\uFE0F ${message}`, NOTICE_DURATION_NORMAL);
}
function showPullInProgressNotice() {
  return new import_obsidian2.Notice("\u23F3 Pulling latest changes\u2026", NOTICE_DURATION_INFO);
}
function showPullSuccessNotice() {
  new import_obsidian2.Notice("\u2B07\uFE0F Pull complete! Vault updated with latest changes.", NOTICE_DURATION_NORMAL);
}
function showPullAlreadyUpToDateNotice() {
  new import_obsidian2.Notice("\u2705 Already up-to-date. No new changes from remote.", NOTICE_DURATION_NORMAL);
}
function showPullErrorNotice(error, app) {
  const { userMessage, technicalDetail } = resolveErrorContent(error);
  const noticeText = technicalDetail ? `\u274C Pull failed: ${userMessage}
(Click for details)` : `\u274C Pull failed: ${userMessage}`;
  const notice = new import_obsidian2.Notice(noticeText, NOTICE_DURATION_ERROR);
  if (technicalDetail) {
    notice.noticeEl.addEventListener("click", () => {
      new GitErrorModal(app, `Pull failed: ${userMessage}`, technicalDetail).open();
    });
    notice.noticeEl.addClass("sgb-notice-clickable");
  }
}
function resolveErrorContent(error) {
  if (error instanceof GitError) {
    return {
      userMessage: gitErrorCodeToMessage(error.code),
      technicalDetail: error.message
    };
  }
  if (error instanceof Error) {
    return {
      userMessage: "An unexpected error occurred during backup.",
      technicalDetail: error.message
    };
  }
  return {
    userMessage: "An unknown error occurred during backup.",
    technicalDetail: String(error)
  };
}
function gitErrorCodeToMessage(code) {
  var _a;
  const messages = {
    GIT_NOT_INSTALLED: "Git is not installed or not on your PATH. Install Git and restart Obsidian.",
    NOT_A_REPO: "This vault is not a Git repository. Run `git init` inside your vault folder.",
    NO_REMOTE: "No Git remote configured. Add one with `git remote add origin <url>`.",
    AUTH_FAILED: "Git authentication failed. Check your SSH key or HTTPS credentials.",
    NETWORK_ERROR: "Network error. Check your internet connection and try again.",
    NOTHING_TO_COMMIT: "Nothing to commit \u2014 the working tree is clean.",
    PUSH_REJECTED: "Push was rejected by the remote. You may need to pull first.",
    TIMEOUT: "Git command timed out (60 s). Check your connection or SSH agent.",
    UNKNOWN_GIT_ERROR: "An unexpected Git error occurred. See details for more information."
  };
  return (_a = messages[code]) != null ? _a : "An unexpected Git error occurred.";
}
var GitErrorModal = class extends import_obsidian2.Modal {
  constructor(app, userMessage, technicalDetail) {
    super(app);
    this.userMessage = userMessage;
    this.technicalDetail = technicalDetail;
  }
  /**
   * Builds the Modal's DOM content.
   * Called by Obsidian when the Modal is opened.
   */
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", {
      text: "Git Backup Error",
      cls: "sgb-modal-title"
    });
    contentEl.createEl("p", {
      text: this.userMessage,
      cls: "sgb-modal-summary"
    });
    contentEl.createEl("h3", {
      text: "Technical details",
      cls: "sgb-modal-detail-heading"
    });
    const pre = contentEl.createEl("pre", { cls: "sgb-modal-detail-pre" });
    pre.createEl("code", { text: this.technicalDetail });
    contentEl.createEl("h3", {
      text: "Common fixes",
      cls: "sgb-modal-detail-heading"
    });
    const tipsList = contentEl.createEl("ul", { cls: "sgb-modal-tips" });
    const tips = [
      "Ensure Git is installed: open a terminal and run `git --version`.",
      "Check the vault is a repo: run `git status` inside your vault folder.",
      "Verify a remote exists: run `git remote -v`.",
      "Confirm authentication works: run `git push` in your terminal."
    ];
    for (const tip of tips) {
      tipsList.createEl("li", { text: tip });
    }
    const buttonRow = contentEl.createEl("div", { cls: "sgb-modal-button-row" });
    const closeBtn = buttonRow.createEl("button", {
      text: "Close",
      cls: "mod-cta sgb-modal-close-btn"
    });
    closeBtn.addEventListener("click", () => this.close());
  }
  /**
   * Cleans up the Modal's DOM when it is closed.
   * Obsidian calls this automatically; we just need to empty the container.
   */
  onClose() {
    this.contentEl.empty();
  }
};

// main.ts
var SeamlessGitBackupPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    /**
     * Track whether a backup is currently in progress to prevent concurrent
     * executions if the user clicks the ribbon button multiple times quickly.
     */
    this.isBackupRunning = false;
    /**
     * Track whether a pull is currently in progress for the same reason.
     * Pull and backup are also mutually exclusive — both touch the Git index.
     */
    this.isPullRunning = false;
  }
  // ─── Lifecycle ─────────────────────────────────────────────────────────────
  /**
   * Called by Obsidian when the plugin is loaded (on startup or after enable).
   *
   * All setup — settings loading, UI registration, command palette, etc. —
   * happens here. Obsidian expects `onload()` to return quickly; async
   * operations (like loading settings from disk) are awaited inside.
   */
  async onload() {
    if (!import_obsidian3.Platform.isDesktop) {
      new import_obsidian3.Notice(
        "Seamless Git Backup requires desktop Obsidian. It uses system Git via Node.js and cannot run on mobile.",
        1e4
      );
      console.warn("[Seamless Git Backup] Plugin disabled: not running on desktop.");
      return;
    }
    await this.loadSettings();
    const vaultPath = this.app.vault.adapter.getBasePath();
    this.gitHandler = new GitHandler(vaultPath);
    this.addRibbonIcon(
      "git-commit-horizontal",
      "Seamless Git Backup: Perform backup now",
      (_event) => {
        void this.executeBackup();
      }
    );
    this.addRibbonIcon(
      "git-pull-request",
      "Seamless Git Backup: Pull latest changes",
      (_event) => {
        void this.executePull();
      }
    );
    this.addCommand({
      id: "trigger-backup",
      name: "Perform Git Backup (commit + push)",
      callback: () => {
        void this.executeBackup();
      }
    });
    this.addCommand({
      id: "trigger-pull",
      name: "Pull latest changes from remote",
      callback: () => {
        void this.executePull();
      }
    });
    this.addSettingTab(new SeamlessGitBackupSettingTab(this.app, this));
    if (this.settings.pullOnStartup) {
      setTimeout(() => {
        void this.executePull({ silent: !this.settings.notifyOnPull });
      }, 0);
    }
    console.log("[Seamless Git Backup] Plugin loaded successfully.");
  }
  /**
   * Called by Obsidian when the plugin is disabled or Obsidian quits.
   *
   * We do not need to explicitly unregister the ribbon icon, commands, or
   * settings tab — Obsidian handles that cleanup automatically. This hook
   * exists for future use (e.g. cancelling in-flight operations, clearing
   * intervals, or cleaning up event listeners added with `.registerEvent()`).
   */
  onunload() {
    console.log("[Seamless Git Backup] Plugin unloaded.");
  }
  // ─── Settings Persistence ──────────────────────────────────────────────────
  /**
   * Loads persisted settings from Obsidian's `data.json` and merges them
   * with `DEFAULT_SETTINGS`.
   *
   * The `Object.assign` merge pattern ensures:
   *  1. Default values are applied for any keys missing from `data.json`
   *     (e.g. after a plugin update that adds a new setting).
   *  2. User values override defaults for all existing keys.
   *  3. We never mutate `DEFAULT_SETTINGS` itself.
   */
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  /**
   * Persists the current `settings` object to `data.json`.
   * Called by the settings tab whenever a control value changes.
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ─── Backup Execution ──────────────────────────────────────────────────────
  /**
   * Orchestrates the full backup flow: pre-flight checks → status → backup.
   *
   * This method is the single entry point called by both the ribbon icon and
   * the command palette. It:
   *  1. Guards against concurrent executions.
   *  2. Runs pre-flight checks (git installed, vault is a repo).
   *  3. Checks for uncommitted changes.
   *  4. Stages, commits, and pushes if changes exist.
   *  5. Handles all errors via `uiHandlers` for a consistent UX.
   */
  async executeBackup() {
    if (this.isBackupRunning) {
      showWarningNotice("A backup is already in progress. Please wait.");
      return;
    }
    this.isBackupRunning = true;
    const progressNotice = showBackupInProgressNotice();
    try {
      await this.gitHandler.checkGitInstallation();
      await this.gitHandler.checkIfRepo();
      const status = await this.gitHandler.getGitStatus();
      if (!status.hasChanges) {
        progressNotice.hide();
        if (this.settings.notifyOnNoChanges) {
          showNoChangesNotice();
        }
        return;
      }
      const commitMessage = resolveCommitMessage(
        this.settings.commitMessageTemplate
      );
      await this.gitHandler.performBackup(commitMessage);
      progressNotice.hide();
      showBackupSuccessNotice();
      console.log(`[Seamless Git Backup] Backup complete. Commit: "${commitMessage}"`);
    } catch (error) {
      progressNotice.hide();
      showBackupErrorNotice(error, this.app);
      console.error("[Seamless Git Backup] Backup failed:", error);
    } finally {
      this.isBackupRunning = false;
    }
  }
  // ─── Pull Execution ────────────────────────────────────────────────────────
  /**
   * Orchestrates a `git pull` with pre-flight checks and UI feedback.
   *
   * @param options.silent - When true, suppresses success/up-to-date notices.
   *   Used for the startup auto-pull so Obsidian opens quietly when there is
   *   nothing new. Errors are always shown regardless of this flag.
   */
  async executePull(options = {}) {
    const { silent = false } = options;
    if (this.isPullRunning) {
      showWarningNotice("A pull is already in progress. Please wait.");
      return;
    }
    if (this.isBackupRunning) {
      showWarningNotice("A backup is in progress. Wait for it to finish before pulling.");
      return;
    }
    this.isPullRunning = true;
    const progressNotice = silent ? null : showPullInProgressNotice();
    try {
      await this.gitHandler.checkGitInstallation();
      await this.gitHandler.checkIfRepo();
      const result = await this.gitHandler.performPull();
      progressNotice == null ? void 0 : progressNotice.hide();
      if (!silent) {
        if (result.alreadyUpToDate) {
          showPullAlreadyUpToDateNotice();
        } else {
          showPullSuccessNotice();
        }
      } else if (!result.alreadyUpToDate) {
        showPullSuccessNotice();
      }
      console.log(
        `[Seamless Git Backup] Pull complete. Up-to-date: ${result.alreadyUpToDate}`
      );
    } catch (error) {
      progressNotice == null ? void 0 : progressNotice.hide();
      showPullErrorNotice(error, this.app);
      console.error("[Seamless Git Backup] Pull failed:", error);
    } finally {
      this.isPullRunning = false;
    }
  }
};
